### ISSUE TITLE
Backup not created on target ftp server because filename contains colons

### ISSUE THREAD

**Issue by pihome3** [sweebee/pimatic-backup#1]
I have installed the backup plugin and have configured it to backup the config to a ftp server on a Asus router.
The backup fails with the error that the file could not be created.
I have found out that the backup file is given a name with a timestamp. That timestamp contains colons in the timepart.
My work around is to add a line to the backup.coffee script:
Orginal line:
             timestamp = new Date().toLocaleString()
Added line:
             timestamp = timestamp.replace /:/g, "_"
Now the backup runs

**Comment by bertreb** [comment]
I created a pull request to solve this

**Comment by sweebee** [comment]
Merge request is merged and i released 0.2.1.
